version: '3.4'

services:
  exercicioresolvido22:
    image: exercicioresolvido22
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
